### ISSUE TITLE
Kafka Connector Connector Editor does not enable the "Submit" button when a value is pasted

### ISSUE THREAD

**Issue by yeikel** [kafbat/kafka-ui#683] opened 2024-11-27 19:24 UTC
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://ui.docs.kafbat.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/kafbat/kafka-ui/issues)
- [X] I've tried running `main`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/kafbat/kafka-ui/blob/main/.github/SECURITY.md)

### Describe the bug (actual behavior)

Kafka Connector Connector Editor does not enable the "Submit" button when a value is pasted

### Expected behavior

It should be enabled

### Your installation details

9c028edcafb4aa1e94c21e9d554951e55035009f

### Steps to reproduce

1. Navigate to an **existing running connector**
2. Click on Config
3. Paste a value in the editor. For example :
   - Both using the keyboard shortcuts and Chrome dialog produce the same bug

```json
{
	"connector.class": "com.google.pubsub.kafka.sink.CloudPubSubSinkConnector",
	"errors.tolerance": "all"
}

```

Expected: The "submit" button is enabled

Actual: The button is not enabled. I need to do manual edits to trigger the event that enables the button

### Screenshots

https://github.com/user-attachments/assets/d8126730-19b6-4503-9e46-26cc6e4b5730

![image](https://github.com/user-attachments/assets/0ed4c553-fa80-4082-ac6d-60ed89b267f7)

### Additional context

This issue may be related to https://github.com/kafbat/kafka-ui/issues/495 although the steps to reproduce are a bit different

**Comment by DimaVilda** [comment] 2024-12-22 20:59
hey hi @yeikel 
I checked it today and could not reproduce a bug. The "Sumbit" functionality works ok for me
check video proof pls

https://github.com/user-attachments/assets/063431ff-592c-40c7-949c-a52d8d62e539

**Comment by yeikel** [comment] 2024-12-22 21:18
> hey hi @yeikel I checked it today and could not reproduce a bug. The "Sumbit" functionality works ok for me check video proof pls
> bug_works.mp4

Your reproducer is a bit different because you made an edit first and then pasted. Can you try, starting from a fresh edit, to paste a value directly? 

1. Create a connector
2. Save
3. Navigate from scratch to to connector and click edit
4. Paste a value

**Comment by Haarolean** [comment] 2024-12-23 14:27
Seems like a dupe of #514
There's a PR (#515), but we'd need some tests for that

**Closed by Haarolean** 2024-12-23 14:27 UTC
Labels: type/bug, status/triage/manual, status/triage/completed
