### ISSUE TITLE
Option to customize refresh interval for the consumer view

### ISSUE THREAD

**Issue by yeikel** [kafbat/kafka-ui#499] opened 2024-07-24 23:11 UTC
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/kafbat/kafka-ui/issues)
- [X] I'm running a supported version of the application which is listed [here](https://github.com/kafbat/kafka-ui/blob/main/.github/SECURITY.md) and the feature is not present there

### Is your proposal related to a problem?

While viewing the customer lag for a consumer, it is unclear what the refresh interval is for that page. If we leave the window long enough it is refreshed but is unclear what the current value is or how to customize it 

![image](https://github.com/user-attachments/assets/54b61ffe-2686-4079-9c3f-e6a11bca64c7)

### Describe the feature you're interested in

I would like to have the option to set how often the UI should poll the backend for updates

### Version you're running

2956664

**Comment by Haarolean** [comment] 2024-08-01 18:02
Kinda a duplicate of #472, please follow that issue

**Closed by Haarolean** 2024-08-01 18:02 UTC
Labels: type/feature, status/triage/manual, status/triage/completed
